apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uc3t1a6hh-python 
  janus-idp.io/tekton: uc3t1a6hh-python
  backstage.io/kubernetes-id: uc3t1a6hh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uc3t1a6hh-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  