apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uc3t1a6hh-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d7c4618dae.pysq.p3.openshiftapps.com/rhtap/rhtap-qe:9fc934136dec1fc93a17dbcec0b98de67aa56211@sha256:7fa25a43a285590e23e4903e51292ee83d3bdb2250c655af6608f33c13c2cf38
          name: container-image
